### ISSUE TITLE
would you be willing to include your orgmode templates?

### ISSUE THREAD

**Issue by japhir** [mwfogleman/.emacs.d#3]
In particular I'm interested in what you created for your [capture templates](https://github.com/mwfogleman/.emacs.d/blob/master/michael.org#capture-templates) `~/org/templates/logtemplate.org` and `~/org/templates/newprojecttemplate.org` after watching your cool [video on daily planning](https://tasshin.com/blog/plan-your-day-daily-time-management-with-emacs-org-mode-and-google-calendar/). I'm assuming the `logtemplate.org` is your daily planning checklist, and I would like to figure out how you set it to automatically clock in etc.

Thanks for sharing so much already!

**Comment by tasshin** [comment]
a) I don't actively use these.
b) I had to remove some things from them, hopefully not anything significant
c) really recommend rolling your own in terms of what's actually in there
[sanitized_templates.zip](https://github.com/mwfogleman/.emacs.d/files/5302169/sanitized_templates.zip)

**Comment by japhir** [comment]
Thanks a lot! I didn't mean to copy the contents of the templates, but look at how you use the metadata toggles (e.g. for automatic clocking in). I think I can figure it out with https://orgmode.org/manual/Template-elements.html and https://orgmode.org/manual/Template-expansion.html#Template-expansion now. Cheers!
